AllCops:
  TargetRubyVersion: 2.6.1
  Exclude:
    - db/*.rb
    - "vendor/**/*"
    - "bin/*"
    - "node_modules/**/*"
  DisplayCopNames: true

Style/Alias:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/Documentation:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/IndentFirstHashElement:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Naming/PredicateName:
  Enabled: false # Doesn't understand `has_secure_token`, though there's promising discussion here: https://github.com/bbatsov/rubocop/issues/1741

Style/Next:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Metrics/LineLength:
  Max: 80

Metrics/ModuleLength:
  Enabled: true
  CountComments: false
  Max: 300
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "app/models/concerns/cobranding_partner_integrations/integratable.rb"

Style/StringLiterals:
  Enabled: false
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: false

Metrics/ParameterLists:
  Max: 6

Layout/DotPosition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/AlignArray:
  Enabled: false

Layout/IndentFirstArrayElement:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

# Disable some New Rules from Rubocop 0.39
Style/FrozenStringLiteralComment:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Description: >-
                 Checks for ambiguous regexp literals in the first argument of
                 a method invocation without parenthesis.
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
